---

name: XML file validation with xmllint

description: "Validates XML files with xmllint"

inputs:
  root_folder:
    description: TODO
    required: false
    default: "."
  file_pattern:
    description: TODO
    required: false
    default: "*.xml"
  huge_files:
    description: TODO
    required: false
    default: false
  validate:
    description: TODO requires a DTD
    required: false
    default: false

outputs:
  errors_html:
    description: TODO
  errors_json:
    description: TODO

runs:
  using: docker
  image: Dockerfile

...
